"""Simulated trade-registry (MERSİS) access — plan section 8.4.

The registry is a **simulated** service and must stay visibly labeled as one in
every UI that shows its data (section 10.1). It lives in a single JSON file:

* ``data/registry.seed.json`` — committed baseline, never written at runtime.
* ``data/registry.json`` — runtime state, regenerated by the demo reset,
  git-ignored.

Writes use a temp file plus an atomic rename under a process-level lock
(section 8.4), so a mid-write crash or a double-click on stage can never leave a
half-written registry behind. Section 15 requires a registry read failure to
**fail closed**: this module raises rather than returning an empty registry, so
a caller cannot mistake "unreadable" for "no representatives".
"""

from __future__ import annotations

import json
import os
import tempfile
import threading
from pathlib import Path

from api.config import Settings, get_settings
from api.schemas import Registry, RegistryCompany, RegistryRepresentativeStatus

# Process-level lock. The demo runs single-process; this guards the FastAPI
# thread pool, where two requests can otherwise interleave read-modify-write.
_WRITE_LOCK = threading.Lock()


class RegistryUnavailableError(RuntimeError):
    """The registry could not be read or parsed. Callers must fail closed."""


def load_seed(settings: Settings | None = None) -> Registry:
    """Read the committed baseline registry."""
    settings = settings or get_settings()
    return _read(settings.registry_seed_path)


def load(settings: Settings | None = None) -> Registry:
    """Read the runtime registry, falling back to the committed seed.

    The fallback exists so a fresh checkout works before the first reset; it
    never silently invents data, because the seed is itself committed input.
    """
    settings = settings or get_settings()
    if settings.registry_path.is_file():
        return _read(settings.registry_path)
    return load_seed(settings)


def get_company(mersis: str, settings: Settings | None = None) -> RegistryCompany | None:
    """Current registry record for a MERSİS number, or None if absent.

    Consulted live on every authorization (GAP-13): the stored authority record
    and the current registry stay separate truths, and the transaction decision
    is where they meet.
    """
    for company in load(settings).companies:
        if company.mersis == mersis:
            return company
    return None


def save(registry: Registry, settings: Settings | None = None) -> None:
    """Atomically replace the runtime registry."""
    settings = settings or get_settings()
    with _WRITE_LOCK:
        _atomic_write(settings.registry_path, registry)


def reset_to_seed(settings: Settings | None = None) -> Registry:
    """Restore the runtime registry to the committed baseline."""
    settings = settings or get_settings()
    with _WRITE_LOCK:
        seed = _read(settings.registry_seed_path)
        _atomic_write(settings.registry_path, seed)
    return seed


def set_representative_status(
    mersis: str,
    rep_id: str,
    status: RegistryRepresentativeStatus,
    settings: Settings | None = None,
) -> RegistryCompany:
    """Address a representative by stable ID and set its status (GAP-09).

    Stable IDs are for addressing; normalized names are for matching. The two
    jobs never share a mechanism.

    Read-modify-write happens entirely inside the lock so two concurrent
    mutations cannot lose one another's change.
    """
    settings = settings or get_settings()
    with _WRITE_LOCK:
        registry = (
            _read(settings.registry_path)
            if settings.registry_path.is_file()
            else _read(settings.registry_seed_path)
        )
        company = next((c for c in registry.companies if c.mersis == mersis), None)
        if company is None:
            raise KeyError(f"registry company {mersis} not found")
        representative = next((r for r in company.representatives if r.id == rep_id), None)
        if representative is None:
            raise KeyError(f"registry representative {rep_id} not found for {mersis}")

        representative.status = status
        _atomic_write(settings.registry_path, registry)
        return company


# ---------------------------------------------------------------------------
# File handling
# ---------------------------------------------------------------------------


def _read(path: Path) -> Registry:
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise RegistryUnavailableError(f"Registry file missing: {path}") from exc
    except json.JSONDecodeError as exc:
        raise RegistryUnavailableError(f"Registry file is not valid JSON: {path}") from exc
    try:
        return Registry.model_validate(raw)
    except Exception as exc:
        raise RegistryUnavailableError(f"Registry file does not match the contract: {path}") from exc


def _atomic_write(path: Path, registry: Registry) -> None:
    """Write via temp file plus rename so the target is never half-written."""
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(
        registry.model_dump(mode="json"), ensure_ascii=False, indent=2, sort_keys=False
    )
    handle, temp_name = tempfile.mkstemp(
        dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp"
    )
    temp_path = Path(temp_name)
    try:
        with os.fdopen(handle, "w", encoding="utf-8") as stream:
            stream.write(payload + "\n")
            stream.flush()
            os.fsync(stream.fileno())
        # os.replace is atomic on both POSIX and Windows.
        os.replace(temp_path, path)
    except BaseException:
        temp_path.unlink(missing_ok=True)
        raise
